"""
Chat model for storing AI conversation history.

This module defines the Chat model which stores all interactions between
users and the AI assistant, including questions, responses, generated SQL
queries, and execution metadata.

Models:
    Chat: Represents a single conversation exchange with the AI.

Example:
    >>> chat = Chat(
    ...     user_id=1,
    ...     question="How much did I spend this month?",
    ...     response="You spent $1,500.00 this month.",
    ...     sql_query="SELECT SUM(amount) FROM transactions WHERE...",
    ...     was_successful=True
    ... )
"""

from sqlalchemy import Column, Integer, Text, Boolean, DateTime, ForeignKey
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship

from app.db.base import Base


class Chat(Base):
    """
    Chat model for AI conversation history.
    
    Stores complete conversation history between users and the AI assistant,
    including questions, AI-generated responses, SQL queries executed to
    gather data, and execution results.
    
    This enables:
    - Conversation history tracking
    - Debugging AI responses
    - Analyzing user behavior patterns
    - Audit trail for data access
    
    Attributes:
        id (int): Primary key, auto-incrementing identifier.
        user_id (int): Foreign key to users table. Links chat to owner.
        question (str): User's question or prompt to the AI.
        response (str): AI's complete response to the user.
        sql_query (str, optional): SQL query generated by AI to fetch data.
            None if no query was needed.
        was_successful (bool): Whether the SQL query executed successfully.
            Default True (for non-query responses).
        error_message (str, optional): Error message if query failed.
            None if query succeeded or no query was executed.
        created_at (datetime): Timestamp when conversation was created.
            Automatically set to current UTC time.
    
    Relationships:
        user (User): Back-reference to the User who owns this chat.
            Access via `chat.user` to get User object.
            Cascade delete: if user is deleted, all chats are deleted.
    
    Table:
        chats: Database table name.
    
    Indexes:
        - id (primary key, automatically indexed)
        - user_id (foreign key, indexed for fast user queries)
    
    Example:
        >>> from app.db.session import SessionLocal
        >>> db = SessionLocal()
        >>> 
        >>> # Create new chat record
        >>> chat = Chat(
        ...     user_id=1,
        ...     question="What's my balance?",
        ...     response="Your current balance is $2,500.00",
        ...     sql_query="SELECT SUM(CASE WHEN type='income'...",
        ...     was_successful=True
        ... )
        >>> db.add(chat)
        >>> db.commit()
        >>> 
        >>> # Query user's chat history
        >>> user_chats = db.query(Chat).filter(Chat.user_id == 1).all()
        >>> for chat in user_chats:
        ...     print(f"Q: {chat.question}")
        ...     print(f"A: {chat.response}")
    
    Notes:
        - All timestamps stored in UTC
        - SQL queries stored for debugging/optimization
        - Soft delete not implemented (hard delete cascade)
        - Text fields have no length limit (use TEXT type)
    
    Version:
        Added in v1.2.0 (AI Chat Feature)
    """
    
    __tablename__ = "chats"
    
    # Primary Key
    id = Column(
        Integer, 
        primary_key=True, 
        index=True,
        comment="Unique identifier for each chat record"
    )
    
    # Foreign Key
    user_id = Column(
        Integer, 
        ForeignKey("users.id"), 
        nullable=False, 
        index=True,
        comment="ID of the user who initiated this conversation"
    )
    
    # Conversation Content
    question = Column(
        Text, 
        nullable=False,
        comment="User's question or prompt sent to the AI"
    )
    
    response = Column(
        Text, 
        nullable=False,
        comment="AI's complete response to the user's question"
    )
    
    # Execution Metadata
    sql_query = Column(
        Text, 
        nullable=True,
        comment="SQL query generated by AI to fetch data (if applicable)"
    )
    
    was_successful = Column(
        Boolean, 
        default=True,
        comment="Whether the SQL query executed successfully"
    )
    
    error_message = Column(
        Text, 
        nullable=True,
        comment="Error message if SQL query failed (null if successful)"
    )
    
    # Timestamps
    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        comment="UTC timestamp when this conversation was created"
    )
    
    # Relationships
    user = relationship(
        "User", 
        back_populates="chats",
        doc="Back-reference to the User who owns this chat"
    )
    
    def __repr__(self) -> str:
        """
        String representation of Chat object for debugging.
        
        Returns:
            str: Readable representation showing key fields.
        
        Example:
            >>> chat = Chat(id=1, user_id=5, question="How much?")
            >>> print(chat)
            <Chat(id=1, user_id=5, question='How much?...')>
        """
        question_preview = self.question[:50] + "..." if len(self.question) > 50 else self.question
        return f"<Chat(id={self.id}, user_id={self.user_id}, question='{question_preview}')>"
